# Generated by Django 5.1.3 on 2025-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
