# Generated by Django 5.1.3 on 2025-09-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0004_facultymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyModel',
        ),
    ]
